"""Create project and document tables

Revision ID: a05529dbd2e0
Revises: 717851e19411
Create Date: 2025-08-17 21:48:34.955996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05529dbd2e0'
down_revision: Union[str, Sequence[str], None] = '717851e19411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('index_status', sa.String(length=50), nullable=True),
    sa.Column('model_status', sa.String(length=50), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('document',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('content_path', sa.String(512), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('prediction', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prediction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_document_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_prediction_id'), 'document', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_document_project_id'), 'document', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_project_id'), table_name='document')
    op.drop_index(op.f('ix_document_prediction_id'), table_name='document')
    op.drop_table('document')
    op.drop_table('project')
    # ### end Alembic commands ###
